meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv
#- dir::../macros/frv_1/frv_1_nl.sv
#- dir::../macros/frv_2/frv_2_nl.sv
#- dir::../macros/frv_4/frv_4_nl.sv
#- dir::../macros/frv_8/frv_8_nl.sv
#- dir::../macros/frv_4ccx/frv_4ccx_nl.sv
#- dir::../macros/frv_1bram/frv_1bram_nl.sv
#- dir::../macros/frv_8bram/frv_8bram_nl.sv
- dir::../ip/rggen-verilog-rtl/rggen_mux.v
- dir::../ip/rggen-verilog-rtl/rggen_bit_field.v
- dir::../ip/rggen-verilog-rtl/rggen_default_register.v
- dir::../ip/rggen-verilog-rtl/rggen_adapter_common.v
- dir::../ip/rggen-verilog-rtl/rggen_register_common.v
- dir::../ip/rggen-verilog-rtl/rggen_wishbone_adapter.v
- dir::../ip/rggen-verilog-rtl/rggen_address_decoder.v
- dir::../ip/rggen-verilog-rtl/rggen_or_reducer.v
- dir::../src/reset_sync.sv
- dir::../src/gen/CSR.v
- dir::../ip/verilog-arbiter/src/arbiter.v
- dir::../ip/wb_intercon/rtl/verilog/wb_cdc.v
- dir::../ip/wb_intercon/rtl/verilog/wb_arbiter.v
- dir::../ip/wb_intercon/rtl/verilog/wb_data_resize.v
- dir::../ip/wb_intercon/rtl/verilog/wb_mux.v    
- dir::../src/gen/wb_intercon.v
- dir::../src/ram512x8.sv
- dir::../src/ram512x32.sv
- dir::../src/wb_ram.sv
- dir::../src/wb_spi.sv
- dir::../src/wb_qspi_mem.sv
- dir::../src/tiny_wb_dma_oled_spi.sv
- dir::../src/hachure_soc.sv
- dir::../ip/EF_IP_UTIL/hdl/ef_util_lib.v
- dir::../ip/EF_UART/hdl/rtl/EF_UART.v
- dir::../ip/EF_UART/hdl/rtl/bus_wrappers/EF_UART_WB.v
- dir::../ip/EF_SPI/hdl/rtl/spi_master.v
- dir::../ip/EF_SPI/hdl/rtl/EF_SPI.v
- dir::../ip/EF_SPI/hdl/rtl/bus_wrappers/EF_SPI_WB.v
- dir::../ip/ahb3lite_wb_bridge/wb_to_ahb3lite.v
- dir::../ip/MS_QSPI_XIP_CACHE/hdl/rtl/MS_QSPI_XIP_CACHE.v
- dir::../ip/MS_QSPI_XIP_CACHE/hdl/rtl/bus_wrappers/MS_QSPI_XIP_CACHE_ahbl.v

LINTER_VLT: dir::../librelane/waivers.vlt

VERILOG_DEFINES:
- CLKG_GF180

VERILOG_INCLUDE_DIRS:
- dir::../ip/rggen-verilog-rtl

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- gf180mcu_hachure_ip__logo
- gf180mcu_fazyrv_ip__logo

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y

CLOCK_PERIOD: 100 # 25 MHz

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.3
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 38
GRT_ALLOW_CONGESTION: true

# Post global placement
DESIGN_REPAIR_MAX_SLEW_PCT: 45
DESIGN_REPAIR_MAX_CAP_PCT: 10
DESIGN_REPAIR_MAX_WIRE_LENGTH: 280

# Post global routing repair
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 35
GRT_DESIGN_REPAIR_MAX_CAP_PCT: 20
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 480

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 15
DRT_ANTENNA_MARGIN: 25 # %

# Fix hold violations
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.3

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75
FP_PDN_VOFFSET: 20

# PDN - Core ring
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# COMP and Poly2 filler cells need to be 
# flattened to form a "filltrans" layer
- "COMP_fill_cell"
- "Poly2_fill_cell"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  gf180mcu_ws_ip__id:
    gds:
      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
    instances:
      chip_id:
        location: [26, 26]
        orientation: N

  gf180mcu_ws_ip__logo:
    gds:
      - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
    instances:
      wafer_space_logo:
        location: ["expr::$DIE_AREA[2] + -169.25", "expr::$DIE_AREA[3] + -169.25"]
        orientation: N

  gf180mcu_hachure_ip__logo:
    gds:
      - dir::../ip/gf180mcu_hachure_ip__logo/gds/gf180mcu_hachure_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_hachure_ip__logo/lef/gf180mcu_hachure_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_hachure_ip__logo/vh/gf180mcu_hachure_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_hachure_ip__logo/lib/gf180mcu_hachure_ip__logo.lib
    instances:
      hachure_logo:
        location: [26, "expr::$DIE_AREA[3] + -169.25"]
        orientation: N

  gf180mcu_fazyrv_ip__logo:
    gds:
      - dir::../ip/gf180mcu_fazyrv_ip__logo/gds/gf180mcu_fazyrv_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_fazyrv_ip__logo/lef/gf180mcu_fazyrv_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_fazyrv_ip__logo/vh/gf180mcu_fazyrv_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_fazyrv_ip__logo/lib/gf180mcu_fazyrv_ip__logo.lib
    instances:
      fazyrv_logo:
        location: ["expr::$DIE_AREA[2] + -169.25", 26]
        orientation: N

  frv_1:
    gds:
      - dir::../macros/frv_1/final/gds/frv_1.gds
    lef:
      - dir::../macros/frv_1/final/lef/frv_1.lef
    vh:
      - dir::../macros/frv_1/final/vh/frv_1.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_1/final/lib/max_tt_025C_5v00/frv_1__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_1/final/lib/max_ff_n40C_5v50/frv_1__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_1/final/lib/max_ss_125C_4v50/frv_1__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_1:
        location: [ 584, 490]
        orientation: N

  frv_2:
    gds:
      - dir::../macros/frv_2/final/gds/frv_2.gds
    lef:
      - dir::../macros/frv_2/final/lef/frv_2.lef
    vh:
      - dir::../macros/frv_2/final/vh/frv_2.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_2/final/lib/max_tt_025C_5v00/frv_2__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_2/final/lib/max_ff_n40C_5v50/frv_2__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_2/final/lib/max_ss_125C_4v50/frv_2__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_2:
        location: [1283, 490]
        orientation: N

  frv_4:
    gds:
      - dir::../macros/frv_4/final/gds/frv_4.gds
    lef:
      - dir::../macros/frv_4/final/lef/frv_4.lef
    vh:
      - dir::../macros/frv_4/final/vh/frv_4.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_4/final/lib/max_tt_025C_5v00/frv_4__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_4/final/lib/max_ff_n40C_5v50/frv_4__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_4/final/lib/max_ss_125C_4v50/frv_4__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_4:
        location: [1989, 490]
        orientation: N

  frv_8:
    gds:
      - dir::../macros/frv_8/final/gds/frv_8.gds
    lef:
      - dir::../macros/frv_8/final/lef/frv_8.lef
    vh:
      - dir::../macros/frv_8/final/vh/frv_8.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_8/final/lib/max_tt_025C_5v00/frv_8__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_8/final/lib/max_ff_n40C_5v50/frv_8__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_8/final/lib/max_ss_125C_4v50/frv_8__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_8:
        location: [2704, 490]
        orientation: N

  frv_4ccx:
    gds:
      - dir::../macros/frv_4ccx/final/gds/frv_4ccx.gds
    lef:
      - dir::../macros/frv_4ccx/final/lef/frv_4ccx.lef
    vh:
      - dir::../macros/frv_4ccx/final/vh/frv_4ccx.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_4ccx/final/lib/max_tt_025C_5v00/frv_4ccx__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_4ccx/final/lib/max_ff_n40C_5v50/frv_4ccx__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_4ccx/final/lib/max_ss_125C_4v50/frv_4ccx__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_4ccx:
        location: [2750, 2030]
        orientation: N

  frv_1bram:
    gds:
      - dir::../macros/frv_1bram/final/gds/frv_1bram.gds
    lef:
      - dir::../macros/frv_1bram/final/lef/frv_1bram.lef
    vh:
      - dir::../macros/frv_1bram/final/vh/frv_1bram.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_1bram/final/lib/max_tt_025C_5v00/frv_1bram__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_1bram/final/lib/max_ff_n40C_5v50/frv_1bram__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_1bram/final/lib/max_ss_125C_4v50/frv_1bram__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_1bram:
        location: [559, 2030]
        orientation: N

  frv_8bram:
    gds:
      - dir::../macros/frv_8bram/final/gds/frv_8bram.gds
    lef:
      - dir::../macros/frv_8bram/final/lef/frv_8bram.lef
    vh:
      - dir::../macros/frv_8bram/final/vh/frv_8bram.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_8bram/final/lib/max_tt_025C_5v00/frv_8bram__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_8bram/final/lib/max_ff_n40C_5v50/frv_8bram__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_8bram/final/lib/max_ss_125C_4v50/frv_8bram__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_8bram:
        location: [559, 1326.5]
        orientation: N


  gf180mcu_fd_ip_sram__sram512x8m8wm1:
    gds:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds
    lef:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lef/gf180mcu_fd_ip_sram__sram512x8m8wm1.lef
    vh:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/verilog/gf180mcu_fd_ip_sram__sram512x8m8wm1__blackbox.v
    lib:
      "*_tt_025C_5v00":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ss_125C_4v50.lib
    instances:
      # Make sure to specify the SRAMs in pdn_cfg.tcl
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [ 500, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [ 500, 3153]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [ 500, 3677]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [ 500, 4207]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [1090, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [1090, 3153]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [1090, 3677]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [1090, 4207]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [1723.5, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [1723.5, 3153]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [1723.5, 3677]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [1723.5, 4207]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [2357, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [2357, 3153]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [2357, 3677]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [2357, 4207]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [2947, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [2947, 3153]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [2947, 3677]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [2947, 4207]
        orientation: E


#ROUTING_OBSTRUCTIONS:
# - [Metal3, 3200, 1325, 3425, 1700] # logo
# - [Metal4, 3200, 1325, 3425, 1700] # logo
# - [Metal5, 3200, 1325, 3425, 1700] # logo
# - [Metal4,  584,  490, 1187,  916] # frv_1
# - [Metal4, 1283,  490, 1895,  922] # frv_2
# - [Metal4, 1989,  490, 2610,  928] # frv_4
# - [Metal4, 2704,  490, 3348,  944] # frv_8
# - [Metal4,  559, 2030, 1248, 2515] # frv_1bram
# - [Metal4, 1550, 1980, 2249, 2373] # frv_8bram
# - [Metal4, 2750, 2030, 3373, 2470] # frv_4ccx


# This is an alternative method compared to
# specifying the power connections in the RTL
# --> Defined in RTL: regex not matching?
PDN_MACRO_CONNECTIONS:
- "i_chip_core.i_hachure_soc.i_frv_1 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_2 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_4 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_8 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_4ccx VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_1bram VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_8bram VDD VSS VDD VSS"
- ".*sram_0 VDD VSS VDD VSS"


# Halo size around macros while cutting rows.
# Workaround for: https://github.com/The-OpenROAD-Project/OpenROAD/issues/8868
FP_MACRO_HORIZONTAL_HALO: 10
FP_MACRO_VERTICAL_HALO: 10
FP_PDN_HORIZONTAL_HALO: 5
FP_PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl

# Make sure netgen doesn't create 'no_connect' nets
# Not needed since netgen 1.5.303
LVS_FLATTEN_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- gf180mcu_hachure_ip__logo
- gf180mcu_fazyrv_ip__logo

# gf180mcu_ws_ip__id/logo has no ports and components
# therefore make it an abstract cell in the layout
MAGIC_EXT_ABSTRACT_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- gf180mcu_hachure_ip__logo
- gf180mcu_fazyrv_ip__logo
