meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    KLayout.Antenna: null
    Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv
#- dir::../macros/frv_1/frv_1_nl.sv
#- dir::../macros/frv_2/frv_2_nl.sv
#- dir::../macros/frv_4/frv_4_nl.sv
#- dir::../macros/frv_8/frv_8_nl.sv
#- dir::../macros/frv_4ccx/frv_4ccx_nl.sv
#- dir::../macros/frv_1bram/frv_1bram_nl.sv
#- dir::../macros/frv_8bram/frv_8bram_nl.sv
- dir::../ip/rggen-verilog-rtl/rggen_mux.v
- dir::../ip/rggen-verilog-rtl/rggen_bit_field.v
- dir::../ip/rggen-verilog-rtl/rggen_default_register.v
- dir::../ip/rggen-verilog-rtl/rggen_adapter_common.v
- dir::../ip/rggen-verilog-rtl/rggen_register_common.v
- dir::../ip/rggen-verilog-rtl/rggen_wishbone_adapter.v
- dir::../ip/rggen-verilog-rtl/rggen_address_decoder.v
- dir::../ip/rggen-verilog-rtl/rggen_or_reducer.v
- dir::../src/reset_sync.sv
- dir::../src/gen/CSR.v
- dir::../ip/verilog-arbiter/src/arbiter.v
- dir::../ip/wb_intercon/rtl/verilog/wb_cdc.v
- dir::../ip/wb_intercon/rtl/verilog/wb_arbiter.v
- dir::../ip/wb_intercon/rtl/verilog/wb_data_resize.v
- dir::../ip/wb_intercon/rtl/verilog/wb_mux.v    
- dir::../src/gen/wb_intercon.v
- dir::../src/ram512x8.sv
- dir::../src/ram512x32.sv
- dir::../src/wb_ram.sv
- dir::../src/wb_spi.sv
- dir::../src/wb_qspi_mem.sv
- dir::../src/tiny_wb_dma_oled_spi.sv
- dir::../src/hachure_soc.sv
- dir::../ip/EF_IP_UTIL/hdl/ef_util_lib.v
- dir::../ip/EF_UART/hdl/rtl/EF_UART.v
- dir::../ip/EF_UART/hdl/rtl/bus_wrappers/EF_UART_WB.v
- dir::../ip/EF_SPI/hdl/rtl/spi_master.v
- dir::../ip/EF_SPI/hdl/rtl/EF_SPI.v
- dir::../ip/EF_SPI/hdl/rtl/bus_wrappers/EF_SPI_WB.v
- dir::../ip/ahb3lite_wb_bridge/wb_to_ahb3lite.v
- dir::../ip/MS_QSPI_XIP_CACHE/hdl/rtl/MS_QSPI_XIP_CACHE.v
- dir::../ip/MS_QSPI_XIP_CACHE/hdl/rtl/bus_wrappers/MS_QSPI_XIP_CACHE_ahbl.v

#LINTER_VLT:
#- dir::../librelane/waivers.vlt

VERILOG_DEFINES:
- CLKG_GF180

VERILOG_INCLUDE_DIRS:
- dir::../ip/rggen-verilog-rtl

# Enable plugin for better SystemVerilog support
# USE_SLANG: True

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    clk_pad,
    rst_n_pad,

    "bidir\\[0\\].pad",
    "bidir\\[1\\].pad",
    "inputs\\[0\\].pad",
    "inputs\\[1\\].pad",
    "inputs\\[2\\].pad",
    "inputs\\[3\\].pad",

    "dvss_pads\\[0\\].pad",

    "inputs\\[4\\].pad",
    "inputs\\[5\\].pad",
    "inputs\\[6\\].pad",
    "inputs\\[7\\].pad",
    "bidir\\[2\\].pad",
    "bidir\\[3\\].pad",
    "bidir\\[4\\].pad",
    "inputs\\[8\\].pad"
]

PAD_EAST: [
    "dvdd_pads\\[0\\].pad",
    "dvss_pads\\[1\\].pad",

    "bidir\\[5\\].pad",
    "bidir\\[6\\].pad",
    "bidir\\[7\\].pad",
    "bidir\\[8\\].pad",
    "bidir\\[9\\].pad",
    "bidir\\[10\\].pad",
    
    "dvdd_pads\\[1\\].pad",
    "dvss_pads\\[2\\].pad",

    
    "bidir\\[11\\].pad",
    "bidir\\[12\\].pad",
    "inputs\\[9\\].pad",
    "inputs\\[10\\].pad",
    "inputs\\[11\\].pad",
    "inputs\\[12\\].pad",
    
    "dvss_pads\\[3\\].pad",
    "dvdd_pads\\[2\\].pad",
    "dvss_pads\\[4\\].pad",
    "dvdd_pads\\[3\\].pad"
]


PAD_NORTH: [
    "bidir\\[24\\].pad",
    "inputs\\[15\\].pad",
    "bidir\\[23\\].pad",
    "bidir\\[22\\].pad",
    "bidir\\[21\\].pad",
    "inputs\\[14\\].pad",
    "bidir\\[20\\].pad",
    "bidir\\[19\\].pad",

    "dvss_pads\\[5\\].pad",

    "bidir\\[18\\].pad",
    "bidir\\[17\\].pad",
    "inputs\\[13\\].pad",
    "bidir\\[16\\].pad",
    "bidir\\[15\\].pad",
    "bidir\\[14\\].pad",
    "bidir\\[13\\].pad",
    "analog\\[0\\].pad"
]


PAD_WEST: [
    "dvdd_pads\\[7\\].pad",
    "dvss_pads\\[9\\].pad",
    "dvdd_pads\\[6\\].pad",
    "dvss_pads\\[8\\].pad",

    "bidir\\[36\\].pad",
    "bidir\\[35\\].pad",
    "bidir\\[34\\].pad",
    "bidir\\[33\\].pad",
    "bidir\\[32\\].pad",
    "bidir\\[31\\].pad",

    "dvdd_pads\\[5\\].pad",
    "dvss_pads\\[7\\].pad",

    "bidir\\[30\\].pad",
    "bidir\\[29\\].pad",
    "bidir\\[28\\].pad",
    "bidir\\[27\\].pad",

    "dvdd_pads\\[4\\].pad",
    "dvss_pads\\[6\\].pad",
    
    "bidir\\[26\\].pad",
    "bidir\\[25\\].pad"
]

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- gf180mcu_hachure_ip__logo

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y

CLOCK_PERIOD: 100 # 25 MHz

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.1

# Floorplanning
FP_SIZING: absolute
# 3880umx5070um including 26um
# for the sealring on all sides
DIE_AREA: [0, 0, 3932, 5122]
CORE_AREA: [442, 442, 3490, 4680]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 55
GRT_ALLOW_CONGESTION: true

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 10
DRT_ANTENNA_MARGIN: 10 # %

# Fix hold violations
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75

# PDN - Core ring
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# COMP and Poly2 filler cells need to be 
# flattened to form a "filltrans" layer
- "COMP_fill_cell"
- "Poly2_fill_cell"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "xdec8_*"
- "prexdec_*"
- "xdec32_*"
- "sa_*"

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  gf180mcu_ws_ip__id:
    gds:
      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
    instances:
      chip_id:
        location: [26, 26]
        orientation: N

  gf180mcu_ws_ip__logo:
    gds:
      - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
    instances:
      wafer_space_logo:
        location: [3762.75, 4952.75]
        orientation: N

  gf180mcu_hachure_ip__logo:
    gds:
      - dir::../ip/gf180mcu_hachure_ip__logo/gds/gf180mcu_hachure_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_hachure_ip__logo/lef/gf180mcu_hachure_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_hachure_ip__logo/vh/gf180mcu_hachure_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_hachure_ip__logo/lib/gf180mcu_hachure_ip__logo.lib
    instances:
      hachure_logo:
        location: [3175, 1325]
        orientation: N

  frv_1:
    gds:
      - dir::../macros/frv_1/final/gds/frv_1.gds
    lef:
      - dir::../macros/frv_1/final/lef/frv_1.lef
    vh:
      - dir::../macros/frv_1/final/vh/frv_1.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_1/final/lib/max_tt_025C_5v00/frv_1__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_1/final/lib/max_ff_n40C_5v50/frv_1__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_1/final/lib/max_ss_125C_4v50/frv_1__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_1:
        location: [ 584, 510]
        orientation: N

  frv_2:
    gds:
      - dir::../macros/frv_2/final/gds/frv_2.gds
    lef:
      - dir::../macros/frv_2/final/lef/frv_2.lef
    vh:
      - dir::../macros/frv_2/final/vh/frv_2.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_2/final/lib/max_tt_025C_5v00/frv_2__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_2/final/lib/max_ff_n40C_5v50/frv_2__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_2/final/lib/max_ss_125C_4v50/frv_2__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_2:
        location: [1283, 510]
        orientation: N

  frv_4:
    gds:
      - dir::../macros/frv_4/final/gds/frv_4.gds
    lef:
      - dir::../macros/frv_4/final/lef/frv_4.lef
    vh:
      - dir::../macros/frv_4/final/vh/frv_4.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_4/final/lib/max_tt_025C_5v00/frv_4__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_4/final/lib/max_ff_n40C_5v50/frv_4__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_4/final/lib/max_ss_125C_4v50/frv_4__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_4:
        location: [1989, 510]
        orientation: N

  frv_8:
    gds:
      - dir::../macros/frv_8/final/gds/frv_8.gds
    lef:
      - dir::../macros/frv_8/final/lef/frv_8.lef
    vh:
      - dir::../macros/frv_8/final/vh/frv_8.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_8/final/lib/max_tt_025C_5v00/frv_8__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_8/final/lib/max_ff_n40C_5v50/frv_8__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_8/final/lib/max_ss_125C_4v50/frv_8__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_8:
        location: [2704, 510]
        orientation: N

  frv_4ccx:
    gds:
      - dir::../macros/frv_4ccx/final/gds/frv_4ccx.gds
    lef:
      - dir::../macros/frv_4ccx/final/lef/frv_4ccx.lef
    vh:
      - dir::../macros/frv_4ccx/final/vh/frv_4ccx.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_4ccx/final/lib/max_tt_025C_5v00/frv_4ccx__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_4ccx/final/lib/max_ff_n40C_5v50/frv_4ccx__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_4ccx/final/lib/max_ss_125C_4v50/frv_4ccx__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_4ccx:
        location: [2725, 2000]
        orientation: N

  frv_1bram:
    gds:
      - dir::../macros/frv_1bram/final/gds/frv_1bram.gds
    lef:
      - dir::../macros/frv_1bram/final/lef/frv_1bram.lef
    vh:
      - dir::../macros/frv_1bram/final/vh/frv_1bram.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_1bram/final/lib/max_tt_025C_5v00/frv_1bram__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_1bram/final/lib/max_ff_n40C_5v50/frv_1bram__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_1bram/final/lib/max_ss_125C_4v50/frv_1bram__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_1bram:
        location: [1148, 2000]
        orientation: N

  frv_8bram:
    gds:
      - dir::../macros/frv_8bram/final/gds/frv_8bram.gds
    lef:
      - dir::../macros/frv_8bram/final/lef/frv_8bram.lef
    vh:
      - dir::../macros/frv_8bram/final/vh/frv_8bram.vh
    lib:
      "*_tt_025C_5v00":
        - dir::../macros/frv_8bram/final/lib/max_tt_025C_5v00/frv_8bram__max_tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - dir::../macros/frv_8bram/final/lib/max_ff_n40C_5v50/frv_8bram__max_ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - dir::../macros/frv_8bram/final/lib/max_ss_125C_4v50/frv_8bram__max_ss_125C_4v50.lib
    instances:
      i_chip_core.i_hachure_soc.i_frv_8bram:
        location: [1931, 2000]
        orientation: N


  gf180mcu_fd_ip_sram__sram512x8m8wm1:
    gds:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds
    lef:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lef/gf180mcu_fd_ip_sram__sram512x8m8wm1.lef
    vh:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/verilog/gf180mcu_fd_ip_sram__sram512x8m8wm1__blackbox.v
    lib:
      "*_tt_025C_5v00":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ss_125C_4v50.lib
    instances:
      # Make sure to specify the SRAMs in pdn_cfg.tcl
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [ 534, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [ 534, 3137]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [ 534, 3667]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[0].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [ 534, 4197]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [1129, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [1129, 3137]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [1129, 3667]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[1].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [1129, 4197]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [1724, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [1724, 3137]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [1724, 3667]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[2].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [1724, 4197]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [2319, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [2319, 3137]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [2319, 3667]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[3].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [2319, 4197]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[0].u_ram.sram_0:
        location: [2914, 2607]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[1].u_ram.sram_0:
        location: [2914, 3137]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[2].u_ram.sram_0:
        location: [2914, 3667]
        orientation: E
      i_chip_core.i_hachure_soc.i_wb_ram.gen_ram_bank[4].i_ram512x32.gen_ram8[3].u_ram.sram_0:
        location: [2914, 4197]
        orientation: E

# This is an alternative method compared to
# specifying the power connections in the RTL
# --> Defined in RTL: regex not matching?
PDN_MACRO_CONNECTIONS:
- "i_chip_core.i_hachure_soc.i_frv_1 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_2 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_4 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_8 VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_4ccx VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_1bram VDD VSS VDD VSS"
- "i_chip_core.i_hachure_soc.i_frv_8bram VDD VSS VDD VSS"
- ".*sram_0 VDD VSS VDD VSS"


# Halo size around macros while cutting rows.
# Workaround for: https://github.com/The-OpenROAD-Project/OpenROAD/issues/8868
FP_MACRO_HORIZONTAL_HALO: 10
FP_MACRO_VERTICAL_HALO: 10
FP_PDN_HORIZONTAL_HALO: 5
FP_PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl

# Make sure netgen doesn't create 'no_connect' nets
# Not needed since netgen 1.5.303
LVS_FLATTEN_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo

# gf180mcu_ws_ip__id/logo has no ports and components
# therefore make it an abstract cell in the layout
MAGIC_EXT_ABSTRACT_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
