
DESIGN_NAME: frv_1
VERILOG_FILES: dir::frv_1_nl.sv
CLOCK_PORT: clk_i
CLOCK_PERIOD: 40 # 40ns = 25MHz

FP_SIZING: relative
#DIE_AREA: [0, 0, 50, 50]
#PDN_MULTILAYER: false
#RT_MAX_LAYER: TopMetal1

CLOCK_PORT: clk_i

FP_ASPECT_RATIO: 0.7
PL_TARGET_DENSITY_PCT: 60

MAX_FANOUT_CONSTRAINT: 8
PL_RESIZER_MAX_SLEW_MARGIN: 5
GLB_RESIZER_MAX_SLEW_MARGIN: 5

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75
PDN_EXTEND_TO: boundary

#PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
#PDN_CORE_RING_VWIDTH: 10
#PDN_CORE_RING_HWIDTH: 10
#PDN_ENABLE_PINS: True
#PDN_CORE_VERTICAL_LAYER: Metal2
#PDN_CORE_HORIZONTAL_LAYER: Metal3

VDD_NETS:
- VDD
GND_NETS:
- VSS

IO_PIN_ORDER_CFG: dir::pin_order.cfg

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6