
DESIGN_NAME: frv_8
VERILOG_FILES: dir::frv_8_nl.sv
CLOCK_PORT: clk_i
CLOCK_PERIOD: 66 # 20ns = 50MHz

FP_SIZING: relative
#DIE_AREA: [0, 0, 50, 50]
#PDN_MULTILAYER: false
#RT_MAX_LAYER: TopMetal1

FP_ASPECT_RATIO: 0.7
PL_TARGET_DENSITY_PCT: 65

MAX_FANOUT_CONSTRAINT: 6

# CTS
CTS_CLK_MAX_WIRE_LENGTH: 0
CTS_DISTANCE_BETWEEN_BUFFERS: 0
CTS_SINK_CLUSTERING_SIZE: 20
CTS_SINK_CLUSTERING_MAX_DIAMETER: 40

# Post global placement
DESIGN_REPAIR_MAX_SLEW_PCT: 35
DESIGN_REPAIR_MAX_CAP_PCT: 30
DESIGN_REPAIR_MAX_WIRE_LENGTH: 400

# Post global routing repair
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 20
GRT_DESIGN_REPAIR_MAX_CAP_PCT: 20
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 600

RUN_POST_GRT_DESIGN_REPAIR: true

GRT_ANTENNA_MARGIN: 20

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75
PDN_EXTEND_TO: boundary

PDN_MULTILAYER: false
RT_MAX_LAYER: Metal4

#PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
#PDN_CORE_RING_VWIDTH: 5
#PDN_CORE_RING_HWIDTH: 5
#PDN_ENABLE_PINS: True
#PDN_CORE_VERTICAL_LAYER: Metal2
#PDN_CORE_HORIZONTAL_LAYER: Metal3

VDD_NETS:
- VDD
GND_NETS:
- VSS

IO_PIN_ORDER_CFG: dir::pin_order.cfg

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6