
DESIGN_NAME: frv_8
VERILOG_FILES: dir::frv_8_nl.sv
CLOCK_PORT: clk_i
CLOCK_PERIOD: 20 # 20ns = 50MHz

FP_SIZING: relative
#DIE_AREA: [0, 0, 50, 50]
#PDN_MULTILAYER: false
#RT_MAX_LAYER: TopMetal1

FP_PDN_CORE_RING: true

FP_ASPECT_RATIO: 0.5

PL_TARGET_DENSITY_PCT: 60



VDD_NETS:
- VDD
GND_NETS:
- VSS

IO_PIN_ORDER_CFG: dir::pin_order.cfg

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6