vlnv: meiniki:gf180fazyrv:wb:0
parameters:
  endian: little
  hosts:
    fazyrv1:
      devices: [qspi_ram_rom, ram, uart, spi, csr]
    fazyrv2:
      devices: [qspi_ram_rom, ram, uart, spi, csr]
    fazyrv4:
      devices: [qspi_ram_rom, ram, uart, spi, csr]
    fazyrv8:
      devices: [qspi_ram_rom, ram, uart, spi, csr]
    oled_dma:
      devices: [qspi_ram_rom, ram] 
  devices:
    qspi_ram_rom:
      offset : 0x00000000
      size   : 0x00010000
    ram:
      offset : 0x20000000
      size   : 0x00010000
    uart:
      offset : 0x30000000
      size   : 0x00000004
    spi:
      offset : 0x40000000
      size   : 0x00000004
    csr:
      offset : 0x50000000
      size   : 0x00000020
